#!/bin/bash
# created mmc mchirico@users.sourceforge.net CopyRight 2003 GPL
# version 0.3.1
#
# Creates a tar.gz file of all files after copying them
# into the $tarfile directory
#
# If you want to auto-upload to sourceforge
# You'll need a .netrc with the following lines:
#      machine upload.sourceforge.net login anonymous password m@aol.com
#         or for all servers
#      default login anonymous password user@site
# Then, if executed with a parameter ./mftp 1
# will upload the file to sourceforge
#
#  Need a quick way to build the array?
#
#   find .  !  \(  -iregex 'pipedup' -o -iregex './pipedup*' -o  -regex '.*svn.*' -o -iname '*mftp' -o -regex '\.' -o -iregex '\.\/\..*'  -o -iregex '.*#.*' -o -iregex '.*gz.*' -o -iregex '.*~.*' -o -iregex './src' -o -iregex './man' \)  |awk '{printf "Array[%d]=\x27%s\x27\n",NR,$0 }'
#
tarfile="pipedup"
if [ -d ${tarfile}  ]
then
  echo "Deleting directory ${tarfile}"
  rm -r  ${tarfile}
fi
# These are the ones to COPY
declare -a Array
Array[1]='./TODO'
Array[2]='./cmds'
Array[3]='./src/wrapper.h'
Array[4]='./src/wrapper.c'
Array[5]='./src/pipedrv.c'
Array[6]='./src/pipedup.c'
Array[7]='./configure.ac'
Array[8]='./man/pipedup.1'
Array[9]='./Makefile'
Array[10]='./VERSION'
Array[11]='./NEWS'
Array[12]='./COPYING'
Array[13]='./README'
Array[14]='./AUTHORS'
Array[15]='./Makefile.am'
Array[16]='./mdo'
Array[17]='./ChangeLog'





























































#
# Create working directory and populate with source files
#
mkdir -p $tarfile
t=""
dashOH=""
for i in `seq ${#Array[@]}`
do
  t="${t} ${dashOH} -ipath '${Array[${i}]}'"
  dashOH='-o'
done
r="find .   \( ${t} \) |cpio -pud ./${tarfile}"

eval $r;














#
#  Standard Upload
#
NOARGS=1
if [ -z $1 ]
then
    echo "  To upload file to sourceforge: `basename $0 ` 1"
    echo "  Run ./mdo and copy configure and Makefile.in to cvs  "
    exit
else

      if [[ $1 == 1 ]]
       then

# You'll need a ~.netrc with the following lines
# machine upload.sourceforge.net login anonymous password m@aol.com

    ftp <<  FTPSTRING
open upload.sourceforge.net
cd incoming
put ${tarfile}.tar.gz
bye
FTPSTRING

       else

# You'll need a ~.netrc with the following lines
# machine upload.sourceforge.net login anonymous password m@aol.com
    ftp <<  FTPSTRING
open upload.sourceforge.net
cd incoming
put ${1}
bye
FTPSTRING




       fi


fi






