.\" Manpage for stock
.\" Contact mchirico@users.sourceforge.com to correct errors or omissions.
.TH GLOGIN(1) "Sat Apr  8 16:07:51 EDT 2006" "1.0" "glogin man page"
.SH NAME
glogin \- Login to Google Accounts
.SH SYNOPSIS
.B glogin -e [email] -p [password] -s [site]
.SH DESCRIPTION
The
.B glogin 
command logs into Google site.



.B glogin -e joe.sample -p Pa33Wrd -s www.linuxaddicted.org
.RS
ACSID = QZJKDJ
.RE

.B glogin 9
.RS
Player: 0 6s,2h <9s,3s,9c,3c,4h> Pocket [6]	2,3,6,9,9
Player: 1 7c,5c <9s,3s,9c,3c,4h> Pocket [flush 20]	3,5,7,9,9
Player: 2 Qc,3d <9s,3s,9c,3c,4h> Pocket [high 26]	3,3,9,9,Q
Player: 3 Kd,Jh <9s,3s,9c,3c,4h> Pocket [bhigh 66]	3,9,9,J,K
Player: 4 Kh,Td <9s,3s,9c,3c,4h> Pocket [bhigh 63]	3,9,9,K,T
Player: 5 As,Qd <9s,3s,9c,3c,4h> Pocket [bhigh 72]	3,9,9,A,Q
Player: 6 9d,6c <9s,3s,9c,3c,4h> Pocket [13]	3,6,9,9,9
Player: 7 Kc,Jd <9s,3s,9c,3c,4h> Pocket [bhigh 66]	3,9,9,J,K
Player: 8 Ac,8s <9s,3s,9c,3c,4h> Pocket [high 40]	3,8,9,9,A
.RE

.SH AUTHOR
Mike Chirico (mchirico@users.sourceforge.net)
.RS
http://souptonuts.sourceforge.net/chirico/index.php
.RE
.SH SOURCE
 http://prdownloads.sourceforge.net/cpearls/glogin.tar.gz?download
.SH SVN
The SVN can be found in the Google Code Chirico project. (This will change)
svn checkout http://chirico.googlecode.com/svn/trunk/c/GoogleAuthenticate  GoogleAuthenticate  
.SH REFERENCES

