#!/bin/bash
# created mmc mchirico@users.sourceforge.net CopyRight 2003 GPL
# version 0.3.0
#
# Creates a tar.gz file of all files after copying them
# into the $tarfile directory
#
# If you want to auto-upload to sourceforge
# You'll need a .netrc with the following lines:
#      machine upload.sourceforge.net login anonymous password m@aol.com
#         or for all servers
#      default login anonymous password user@site
# Then, if executed with a parameter ./mftp 1
# will upload the file to sourceforge
#
#  Need a quick way to build the array?
#    find .  !  \(  -iregex '.*simple_but_common.*'  -o -regex './separate_compilation' -o -regex '.*\.svn.*' -o -iname '*mftp*' -o -regex '\.' -o -iregex '\.\/\..*'  -o -iregex '.*#.*' \)  |awk '{printf "Array[%d]=\x27%s\x27\n",NR,$0 }'
#
#    ls separate_compilation/*.h  separate_compilation/*.c separate_compilation/README separate_compilation/Makefile *.cc *.h *.c Make* *.old *.sql VERSION README COPYING NOTES ascii ChangeLog CHANGELOG TODO |awk '{printf "Array[%d]=\x27./%s\x27\n",NR,$0 }'
#
tarfile="simple_but_common"
if [ -d ${tarfile}  ]
then
  echo "Deleting directory ${tarfile}"
  rm -r  ${tarfile}
fi
if [ -f ${tarfile}.tar.gz ]
then
  rm ${tarfile}.tar.gz
fi
# These are the ones to COPY
declare -a Array
Array[1]='./NOTES'
Array[2]='./openstrip.c'
Array[3]='./pam_example.c'
Array[4]='./ls.c'
Array[5]='./system.c'
Array[6]='./gdbm_ex1.c'
Array[7]='./errno.c'
Array[8]='./README'
Array[9]='./rawsockets.c'
Array[10]='./btree.c'
Array[11]='./rtctime.c'
Array[12]='./server.c'
Array[13]='./mntquota.c'
Array[14]='./autoscan.log'
Array[15]='./pipedrv2.c'
Array[16]='./regexp.c'
Array[17]='./sizediff.c'
Array[18]='./ChangeLog'
Array[19]='./enum.cc'
Array[20]='./pipe_dup2.c'
Array[21]='./COPYING'
Array[22]='./myassert.cc'
Array[23]='./Makefile'
Array[24]='./smtp.c'
Array[25]='./getline.c'
Array[26]='./open.c'
Array[27]='./pcap_ex1.c'
Array[28]='./popen.c'
Array[29]='./rand.c'
Array[30]='./regex2.c'
Array[31]='./simpleClass.cc'
Array[32]='./getopt.c'
Array[33]='./dnotify.c'
Array[34]='./separate_compilation/README'
Array[35]='./separate_compilation/stuff.c'
Array[36]='./separate_compilation/Makefile'
Array[37]='./separate_compilation/user.c'
Array[38]='./separate_compilation/stuff.h'
Array[39]='./pipe.c'
Array[40]='./read.c'
Array[41]='./printfLongdouble.c'
Array[42]='./syslog.c'
Array[43]='./getpwuid.c'
Array[44]='./VERSION'
Array[45]='./opendir.c'
Array[46]='./realloc.c'
Array[47]='./uid_open.c'
Array[48]='./readrealloc.c'
Array[49]='./pipedrv.c'
Array[50]='./ascii'










































































mkdir -p $tarfile

t=""
dashOH=""
for i in `seq ${#Array[@]}`
do
  t="${t} ${dashOH} -ipath '${Array[${i}]}'"
  dashOH='-o'

done



#r="find .   \( $t \)  -exec cp -r {} ./$tarfile/. \;"
r="find .  \( $t \) |cpio -pud ./${tarfile}"

#
#
eval $r
tar -czf $tarfile".tar.gz" $tarfile

#
#  Standard Upload
#
NOARGS=1
if [ -z $1 ]
then
    echo "  To upload file to sourceforge: `basename $0 ` 1"
    exit
else
# You'll need a ~.netrc with the following lines
# machine upload.sourceforge.net login anonymous password m@aol.com
    ftp <<  FTPSTRING
open upload.sourceforge.net
cd incoming
put ${tarfile}.tar.gz
bye
FTPSTRING


fi
