#!/bin/bash
# created mmc mchirico@users.sourceforge.net CopyRight 2003 GPL
# version 0.3.1
#
# Creates a tar.gz file of all files after copying them
# into the $tarfile directory
#
# If you want to auto-upload to sourceforge
# You'll need a .netrc with the following lines:
#      machine upload.sourceforge.net login anonymous password m@aol.com
#         or for all servers
#      default login anonymous password user@site
# Then, if executed with a parameter ./mftp 1
# will upload the file to sourceforge
#
#  Need a quick way to build the array?
#
#   find .  !  \(  -iregex './ssl_tls.*' -o -regex '.*svn.*' -o  -regex '.*CVS.*' -o -iname '*mftp' -o -regex '\.' -o -iregex '\.\/\..*'  -o -iregex '.*#.*' -o -iregex '.*gz.*' -o -iregex '.*~.*' -o -iregex './src' -o -iregex './man' \)  |awk '{printf "Array[%d]=\x27%s\x27\n",NR,$0 }'
#
tarfile="ssl_tls"
if [ -d ${tarfile}  ]
then
  echo "Deleting directory ${tarfile}"
  rm -r  ${tarfile}
fi
# These are the ones to COPY
declare -a Array
Array[1]='./configure.ac'
Array[2]='./VERSION'
Array[3]='./scripts'
Array[4]='./scripts/Notes'
Array[5]='./scripts/smtp_scripts.pl'
Array[6]='./man/tlssmtp.1'
Array[7]='./man/tlsserver.1'
Array[8]='./man/tlstutorial.1'
Array[9]='./man/tlsimap.1'
Array[10]='./COPYING'
Array[11]='./AUTHORS'
Array[12]='./mdo'
Array[13]='./configure'
Array[14]='./Makefile.am'
Array[15]='./TODO'
Array[16]='./INSTALL'
Array[17]='./README'
Array[18]='./NEWS'
Array[19]='./Makefile'
Array[20]='./password_smtp_64'
Array[21]='./ChangeLog'
Array[22]='./src/tlsserver.c'
Array[23]='./src/sslpop3.c'
Array[24]='./src/tlssmtp.c'
Array[25]='./src/tlsimap.c'
Array[26]='./password_file'






































































#
# Create working directory and populate with source files
#
mkdir -p $tarfile
t=""
dashOH=""
for i in `seq ${#Array[@]}`
do
  t="${t} ${dashOH} -ipath '${Array[${i}]}'"
  dashOH='-o'
done
r="find .   \( ${t} \) |cpio -pud ./${tarfile}"

eval $r;














#
#  Standard Upload
#
NOARGS=1
if [ -z $1 ]
then
    echo "  To upload file to sourceforge: `basename $0 ` 1"
    echo "  Run ./mdo and copy configure and Makefile.in to cvs  "
    exit
else

      if [[ $1 == 1 ]]
       then

# You'll need a ~.netrc with the following lines
# machine upload.sourceforge.net login anonymous password m@aol.com

    ftp <<  FTPSTRING
open upload.sourceforge.net
cd incoming
put ${tarfile}.tar.gz
bye
FTPSTRING

       else

# You'll need a ~.netrc with the following lines
# machine upload.sourceforge.net login anonymous password m@aol.com
    ftp <<  FTPSTRING
open upload.sourceforge.net
cd incoming
put ${1}
bye
FTPSTRING




       fi


fi






