#!/bin/bash
export VERSION=redis-2.2.14

IP=$(hostname -i)
perl -pi.backup -e "s/bind localhost/bind ${IP}/" redis.conf

echo "Cleaning up"
[ -f ${VERSION}.tar.gz ] && rm -rf ${VERSION}.tar.gz
[ -d ${VERSION} ] && rm -rf ${VERSION}
echo "First step download files"
wget http://redis.googlecode.com/files/${VERSION}.tar.gz
echo "Now untar"
tar -xzf ${VERSION}.tar.gz

cd ${VERSION}
make
echo "You'll now need to install redis"
echo "sudo mdo_root"


