#!/bin/bash
#  Copyright (C) 2003  Mike Chirico mmc mchirico@users.sourceforge.net GPL
#	
#	Find with prune using arrays
#	
#
#
tarfile="bashscripts.0.0.1q"
# These are the files to be ignored
declare -a Array
Array[1]='.*/CVS'   # index with 1 when using seq command
Array[2]='.*/a.out'
Array[3]='.*~'
Array[4]='.*/1'
Array[5]='.*#.*'
Array[6]='./*.gz'
Array[7]='./*.tar'
Array[8]='./junk'
Array[9]='./main'
Array[10]='./'`basename $0`
#
#  The next commands create the -regex expressions 
#  from the array above
#
t=""
dashOH=""
for i in `seq ${#Array[@]}`
do
  t="${t} ${dashOH} -iregex '${Array[${i}]}'"
  dashOH='-o'

done
r="find . -type f  \( $t \) -prune -o   -print"
eval $r
