#!/bin/bash
# created mmc mchirico@users.sourceforge.net CopyRight 2003 GPL
# version 0.3.0
#
# Creates a tar.gz file of all files after copying them
# into the $tarfile directory
#
# If you want to auto-upload to sourceforge
# You'll need a .netrc with the following lines:
#      machine upload.sourceforge.net login anonymous password m@aol.com
#         or for all servers
#      default login anonymous password user@site
# Then, if executed with a parameter ./mftp 1
# will upload the file to sourceforge
#
#  Need a quick way to build the array?
#    cat fileLIST |awk '{printf "Array[%d]=\x27./%s\x27\n",NR,$0 }'
#
tarfile="bashscripts.0.0.3"
if [ -d ${tarfile}  ]
then
  echo "Deleting directory ${tarfile}"
  rm -r  ${tarfile}
fi
if [ -f ${tarfile}.tar.gz ]
then
  rm ${tarfile}.tar.gz
fi
# These are the ones to COPY
declare -a Array
Array[1]='./MySQLbackup'
Array[2]='./COPYING'
Array[3]='./basharray1'
Array[4]='./NOTES'
Array[5]='./README'
Array[6]='./bcsample1'
Array[7]='./bcfile1'
Array[8]='./kernelver'
Array[9]='./clean'
Array[10]='./find1'
Array[11]='./diff_patch_sample'
Array[12]='./dirlistandvar'
Array[13]='./email_ftp_changes'
Array[14]='./find2'
Array[15]='./forloop'
Array[16]='./getopts'
Array[17]='./listmount'
Array[18]='./listprocess'
Array[19]='./listprocess.c'
Array[20]='./mreplace'
Array[21]='./mreturn'
Array[22]='./myMakeTar'
Array[23]='./myloclns'
Array[24]='./numargs'
Array[25]='./sfu'
Array[26]='./sshack1'
Array[27]='./targzdecrypt'
Array[28]='./targzencrypt'
Array[29]='./test1.c'
Array[30]='./test1.c.original'
Array[31]='./test2.c'
Array[32]='./whoisbooting'
Array[33]='./sourceforgebackup'
Array[34]='./getgid.c'
Array[35]='./find_prune'
Array[36]='./need_to_access'
Array[37]='./taperestore'
Array[38]='./kill9user'
Array[39]='./README_BASH'
Array[40]='./getpwuid.c'
Array[41]='./tapebackup'
Array[42]='./remove_old_log_files'
Array[43]='./DEFINITIONS'
Array[44]='./myMakeTar3'
Array[45]='./diskhog'
Array[46]='./faqget'
























mkdir -p $tarfile

t=""
dashOH=""
for i in `seq ${#Array[@]}`
do
  t="${t} ${dashOH} -ipath '${Array[${i}]}'"
  dashOH='-o'

done



#r="find .   \( $t \)  -exec cp -r {} ./$tarfile/. \;"
r="find .   \( $t \) |cpio -pud ./${tarfile}"

#
#
eval $r
tar -czf $tarfile".tar.gz" $tarfile

#
#  Standard Upload
#
NOARGS=1
if [ -z $1 ]
then
    echo "  To upload file to sourceforge: `basename $0 ` 1"
    exit
else
# You'll need a ~.netrc with the following lines
# machine upload.sourceforge.net login anonymous password m@aol.com
    ftp <<  FTPSTRING
open upload.sourceforge.net
cd incoming
put ${tarfile}.tar.gz
bye
FTPSTRING


fi
