#!/bin/bash
BOLD=`tput smso`
NORMAL=`tput rmso`
export BOLD NORMAL
tput clear
tput cup 5 15
echo "${BOLD}Myscript1${NORMAL}"
tput cup 14 10; echo -e "Please enter any key to continue ..\b\c"
read answer
error_flag=0
while true
do
 if [ $error_flag -eq 0 ]
 then
   tput clear
   tput cup 5 10
   echo "Myscript1 - ${BOLD}MAIN MENU${NORMAL}"
   tput cup 7 20; echo "0: ${BOLD}EXIT${NORMAL} this program"
   tput cup 9 20; echo "1: ${BOLD}DATE${NORMAL}"
   tput cup 11 20; echo "2: ${BOLD}CALENDAR${NORMAL}"
 fi
tput cup 13 10; echo -e "Enter your choice> _\b\c"
read choice
 case $choice in
      0) tput clear; exit 0;;
      1) date;;
      2) cal -y;;
 esac

read;

done
exit 0

